#!/usr/bin/env python3
"""Generate README.md and validation_report.md from the measured data in build/*.json (no hand-typed numbers)."""
import os, json
import params as P
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
V = json.load(open(f"{ROOT}/build/validation.json")); S = json.load(open(f"{ROOT}/build/slicing.json"))
bb = V["assembled_bbox_mm"]; hj = V["head_joint"]; tj = V["tail_joint"]; hd = hj["dimensions_mm"]; td = tj["dimensions_mm"]
lim = hj["collision_free_limits_deg"]; ha = hj["assembly"]; ta = tj["assembly"]
URL = "https://drive.google.com/file/d/13HVwXR2jKd8h_SItTTXizeP983Ik6S_V/view?usp=drivesdk"
def sl(n): return S[n]
tot_g = sum(float(S[n]["filament_g"]) for n in ("body", "head", "tail"))

readme = f"""# Articulated dog — a child's drawing as a printable toy

![drawing to toy](renders/presentation.png)

A 3-part, glue-free, FDM-printable toy built directly from a child's pencil drawing of a dog
(long level back, boxy belly, four chunky legs, small head with two pointed ears, big tail hooking upward).
The side silhouette follows the drawing; the drawing's quirks are kept on purpose (the belly box, the
side-by-side legs and ears that a child draws to show "both", the blunt muzzle).

It has **exactly two joints**: the **head** (ball joint) and the **tail** (swivel). Everything else is one solid piece.

* Source image: {URL}  (copy included unmodified as `source_drawing.jpg`)
* Everything is generated by the scripts in `scripts/` — change `scripts/params.py` and re-run to modify.

## Final dimensions (assembled, neutral pose)

| | mm |
|---|---|
| Length (tail to nose) | **{bb['length_x']}** |
| Width | **{bb['width_y']}** |
| Height (floor to tail top) | **{bb['height_z']}** |

## Parts

| File | Qty | Print size (mm) | Volume | Notes |
|---|---|---|---|---|
| `stl/body.stl` | 1 | {' x '.join(map(str, V['meshes']['stl/body.stl']['bbox_mm']))} | {V['meshes']['stl/body.stl']['volume_cm3']} cm³ | torso, 4 legs, ball stud for the head, bore for the tail |
| `stl/head.stl` | 1 | {' x '.join(map(str, V['meshes']['stl/head.stl']['bbox_mm']))} | {V['meshes']['stl/head.stl']['volume_cm3']} cm³ | socket in the flat underside |
| `stl/tail.stl` | 1 | {' x '.join(map(str, V['meshes']['stl/tail.stl']['bbox_mm']))} | {V['meshes']['stl/tail.stl']['volume_cm3']} cm³ | split snap-pin at the root |

The STLs in `stl/` are already in their print orientation. `dog_print.3mf` holds all three on one plate.
`dog_assembled.stl` / `dog_preview.glb` / `dog_complete.blend` show the assembled toy (in the .blend, rotate the
two `JOINT_*` empties to pose it). No separate joint parts and no hardware are needed.

## Joint A — head: slotted ball-and-socket (snap-on)

* A Ø{hd['ball_diameter']} mm ball on a Ø{hd['stalk_diameter']} mm stalk stands vertically on the neck of the body.
  A {hd['slot_width']} mm slot splits ball and stalk into two halves that flex towards each other; a {round((hd['moat_outer_diameter']-hd['stalk_diameter'])/2,2)} mm wide
  relief moat around the stalk makes the flexing length {hd['flex_length']} mm. The ball has two flats
  ({hd['ball_width_across_flats']} mm across) so the squeezed halves can actually pass the round throat.
* The head has a rigid Ø{hd['socket_diameter']} mm spherical socket reached through a tapered tunnel from its flat underside
  (throat Ø{hd['throat_diameter']} mm). The socket roof is a 45° cone so it prints without support.
* Fit: radial clearance {hd['radial_clearance']} mm sphere-to-sphere, but each ball half is modelled {hd['ball_half_spread']} mm
  outward, giving a deliberate **{hd['preload_interference_per_side']} mm elastic preload per side**. That preload — not a tight
  rigid fit — is what holds the head where you put it and absorbs printer tolerance.
* Movement (collision-checked): **turn left/right ±{int(P.HEAD_YAW)}°** (hard stop at about ±{int(lim['yaw_left'])}°),
  **nod ±{int(P.HEAD_PITCH)}°** (stop ≈ {int(lim['pitch_nose_down'])}°), **sideways tilt ±{int(P.HEAD_ROLL)}°** (stop ≈ {int(lim['roll_pos'])}°).

## Joint B — tail: swivel on a split snap-pin

* The tail root carries a Ø{td['peg_diameter']} mm pin, {td['peg_length']} mm long, split by a {td['slot_width']} mm slot into two
  {td['arm_thickness']} mm arms with a barb (Ø{td['barb_diameter']} mm) at the tip.
* The body has a vertical Ø{td['bore_diameter']} mm bore ({td['bore_depth']} mm deep) with an undercut (Ø{td['undercut_cavity_diameter']} mm) and a
  45° ledge. The barbs snap under the ledge ({td['barb_engagement_per_side']} mm engagement per side).
* Fit: radial clearance {td['radial_clearance']} mm; a friction band on the arms is {td['friction_band_interference_radial']} mm oversize on radius so the
  arms press lightly on the bore and the tail stays where it is put. Axial play ≈ {tj['axial_play_mm']} mm.
* Movement: **full 360° rotation** about the vertical axis — the hook can point forward (as drawn), sideways or back.
* The root is the same {td['peg_across_flats']} mm thick as the tail, printed flat so the layers run along the snap arms.

## Printing

| Setting | Recommendation |
|---|---|
| Filament | PLA (PETG also fine and a little more forgiving on the snaps) |
| Nozzle / layer | 0.4 mm / 0.20 mm |
| Perimeters | 4 (3 minimum) — the ball stalk and the pin arms are then solid perimeters |
| Infill | 15 % |
| Top / bottom | 5 / 4 layers |

| Part | Orientation | Supports |
|---|---|---|
| body | standing on its four feet (as in the STL) | **yes — "supports on build plate only"**, under belly box, torso and between the legs. None are needed inside the tail bore or around the ball. |
| head | flat underside on the bed (as in the STL) | **none** — do not enable supports, they would fill the socket |
| tail | lying on its flat side (as in the STL) | **none** |

Slicer estimates (PrusaSlicer, settings above): body {sl('body')['print_time']} / {sl('body')['filament_g']} g,
head {sl('head')['print_time']} / {sl('head')['filament_g']} g, tail {sl('tail')['print_time']} / {sl('tail')['filament_g']} g — about {tot_g:.0f} g in total.
If you open `dog_print.3mf`, switch supports on for the body only.

## Assembly (no glue, no tools)

1. Remove the supports from under the body. Check the slot in the ball and the moat around the stalk are clear.
2. **Tail:** hold the tail above the hole in the rump and push straight down until it clicks
   (the arms need to squeeze {ta['required_deflection_per_arm_mm']} mm each; the slot allows {ta['available_deflection_per_arm_mm']} mm).
3. **Head:** set the hole in the underside of the head over the ball and push straight down until it snaps
   (each ball half squeezes {ha['required_deflection_per_half_mm']} mm; the slot allows {ha['available_deflection_per_half_mm']} mm). Push on the top of the head between the ears, not on the ears.
4. Both joints can be pulled off again with a firm straight pull.

## Optional tolerance test (`test/joint_tolerance_test.stl`)

Four small pieces, already in print orientation, no supports ({sl('joint_tolerance_test')['print_time']}, {sl('joint_tolerance_test')['filament_g']} g):

* a block with three head sockets — radial clearance **0.00 / 0.10 / 0.20 mm**, marked with 1 / 2 / 3 notches
  (2 notches = the production head),
* the production ball stud on a small base,
* a block with the production tail bore, and the production tail pin on a handle.

The ball should snap into the 2-notch socket with a firm push and then turn smoothly with noticeable friction.
If only the 3-notch socket feels right, set `SOCKET_CLEAR = 0.20` in `scripts/params.py`; if the 1-notch one does,
set `0.00`; then re-run `generate.py`. For the tail, adjust `BORE_CLEAR` (looser/tighter turning) or `BAND_INTERF` (friction).

## Reproducing

```
pip install numpy scipy scikit-image trimesh manifold3d shapely rtree pillow networkx lxml
cd scripts
python3 generate.py            # shells (SDF) + joints (CSG) -> stl/, dog_assembled.stl
python3 make_test.py           # tolerance test piece
python3 make_3mf.py            # dog_print.3mf
python3 validate.py            # mesh / collision / assembly / stability checks -> build/validation.json
python3 slice_all.py           # PrusaSlicer CLI on every part -> build/slicing.json
blender -b -P render_blender.py   # renders, dog_complete.blend, dog_preview.glb
python3 silhouette_compare.py; python3 presentation.py; python3 build_docs.py
```
See `validation_report.md` for all measured values and known compromises.
"""
open(f"{ROOT}/README.md", "w").write(readme)

def yn(b): return "yes" if b else "**NO**"
rows = ""
for f, m in V["meshes"].items():
    rows += f"| `{f}` | {m['triangles']} | {yn(m['watertight'])} | {yn(m['every_edge_shared_by_exactly_2_faces'])} / {m['manifold3d_status']} | {yn(m['outward_normals'] and m['winding_consistent'])} | {m['components']} | {m['zero_area_faces']} | {m['duplicate_faces']} | {yn(m['self_intersection_free'])} | {' x '.join(map(str, m['bbox_mm']))} |\n"
srows = ""
for n in ("body", "head", "tail", "joint_tolerance_test", "plate_3mf"):
    s = S[n]; sup = s["extrusion_share_percent"].get("Support material", 0) + s["extrusion_share_percent"].get("Support material interface", 0)
    srows += f"| `{s['file']}` | {yn(s['sliced_ok'])} | {len(s['slicer_messages'])} | {s['layers']} | {s['print_time']} | {s['filament_g']} g | {'on (build plate only)' if s['supports_enabled'] else 'off'} | {sup:.1f} % | {s.get('bed_contact_area_mm2', '-')} |\n"
gaps = "\n".join(f"| {g['yaw']} | {g['pitch']} | {g['roll']} | {g['min_gap_mm']} |" for g in hj["min_gap_samples"])
st = "\n".join(f"| {s['pose']} | {s['com_mm']} | {s['min_margin_to_support_edge_mm']} | {s['tip_over_angle_deg']}° |" for s in V["stability"])
w = V["wall_thickness_mm"]
rep = f"""# Validation report

All numbers below were measured by `scripts/validate.py` (trimesh + manifold3d) and `scripts/slice_all.py`
(PrusaSlicer CLI) on the delivered files; raw data: `build/validation.json`, `build/slicing.json`.

## 1. Dimensions

Assembled, neutral pose: **{bb['length_x']} x {bb['width_y']} x {bb['height_z']} mm** (length x width x height).
Solid volume {sum(V['meshes'][f'stl/{n}.stl']['volume_cm3'] for n in ('body','head','tail')):.1f} cm³.

## 2. Mesh quality

| File | Triangles | Watertight | 2-manifold edges / manifold3d status | Outward normals | Shells | Zero-area faces | Duplicate faces | Free of self-intersection | Bounding box (mm) |
|---|---|---|---|---|---|---|---|---|---|
{rows}
`dog_assembled.stl` intentionally contains 3 shells (body, head, tail in place, shown in their installed state);
the test file contains 4 separate test pieces. Each production STL is a single shell.

## 3. Joint A — head ball joint

| Quantity | Value |
|---|---|
| Ball diameter / width across flats | {hd['ball_diameter']} / {hd['ball_width_across_flats']} mm |
| Socket diameter | {hd['socket_diameter']} mm (radial clearance {hd['radial_clearance']} mm) |
| Ball-half spread (as printed) | {hd['ball_half_spread']} mm per side -> elastic preload interference {hd['preload_interference_per_side']} mm per side (overlap volume {hd['preload_overlap_volume_mm3']} mm³) |
| Throat diameter | {hd['throat_diameter']} mm |
| Stalk diameter / slot / moat outer diameter | {hd['stalk_diameter']} / {hd['slot_width']} / {hd['moat_outer_diameter']} mm |
| Flexing length / half-stalk thickness | {hd['flex_length']} / {hd['half_stalk_thickness']} mm |
| Min. head wall around socket + tunnel | {w['head_around_socket_min']} mm |
| Ball stalk cross-section (each half, at z = 60) | {w['ball_stalk_section_at_z60']} mm |

**Range of motion.** {hj['poses_tested']} poses were tested over yaw ±{int(P.HEAD_YAW)}° (15° steps) x nod ±{int(P.HEAD_PITCH)}° (5° steps) x
sideways tilt ±{int(P.HEAD_ROLL)}° (6° steps), limited to a combined tilt of {P.HEAD_TILT_TOTAL}°, with the ball in its installed state:
maximum body/head interference volume = **{hj['max_interference_volume_mm3']} mm³**.

Single-axis hard stops (last collision-free angle): yaw {lim['yaw_right']}° … +{lim['yaw_left']}°, nod {lim['pitch_nose_up']}° … +{lim['pitch_nose_down']}°,
sideways tilt {lim['roll_neg']}° … +{lim['roll_pos']}°.

Minimum body-to-head gap at sample poses (the 0.096 mm value is the ball/socket clearance itself, nominal 0.10):

| yaw | nod | tilt | min gap (mm) |
|---|---|---|---|
{gaps}

**Assembly path** ({ha['direction']}): pushing the parts together rigidly gives up to {ha['max_overlap_rigid_mm3']} mm³ overlap
(= the snap). With both ball halves deflected inward the path becomes collision-free at **{ha['required_deflection_per_half_mm']} mm per half**;
the slot allows {ha['available_deflection_per_half_mm']} mm. Estimated peak bending strain while snapping ≈ {hd['est_peak_strain_assembly_percent']} %,
sustained strain from the preload ≈ {hd['est_sustained_strain_percent']} % (beam estimate).
**Retention:** lifting the seated head 1 mm rigidly produces {hj['retention_overlap_when_lifted_1mm_mm3']} mm³ of overlap at the throat, i.e. it cannot come off without re-squeezing the ball.

## 4. Joint B — tail swivel

| Quantity | Value |
|---|---|
| Pin diameter / across flats / length | {td['peg_diameter']} / {td['peg_across_flats']} / {td['peg_length']} mm |
| Bore diameter / depth | {td['bore_diameter']} / {td['bore_depth']} mm (radial clearance {td['radial_clearance']} mm) |
| Barb diameter / engagement per side | {td['barb_diameter']} / {td['barb_engagement_per_side']} mm |
| Undercut cavity diameter | {td['undercut_cavity_diameter']} mm |
| Friction band diameter | {td['friction_band_diameter']} mm ({td['friction_band_interference_radial']} mm radial preload) |
| Slot / arm thickness / arm flex length | {td['slot_width']} / {td['arm_thickness']} / {td['arm_flex_length']} mm |
| Axial play | {tj['axial_play_mm']} mm |
| Min. body wall around bore and undercut | {w['body_around_tail_bore_min']} mm |

**Range of motion.** Full 360°, tested every 10° ({tj['angles_tested']} positions). The only body/tail overlap is the intended friction band
({tj['overlap_volume_mm3_min_max'][0]}–{tj['overlap_volume_mm3_min_max'][1]} mm³, constant with angle, confined to the band: {yn(tj['overlap_confined_to_intentional_friction_band'])}).
With the band excluded: interference **{tj['max_interference_excluding_band_mm3']} mm³**, minimum gap {tj['min_gap_excluding_band_mm']} mm.

**Assembly path** ({ta['direction']}): rigid overlap up to {ta['max_overlap_rigid_mm3']} mm³ (the snap); collision-free once each arm is deflected
**{ta['required_deflection_per_arm_mm']} mm** (slot allows {ta['available_deflection_per_arm_mm']} mm). Estimated peak strain ≈ {td['est_peak_strain_percent']} %, with layers running along the arms.
**Retention:** lifting the seated tail 2 mm rigidly gives {tj['retention_overlap_when_lifted_2mm_mm3']} mm³ overlap (barbs on the ledge).

## 5. Feature thickness

| Feature | Measured section (mm) |
|---|---|
| Legs at 15 mm above floor (each of 4) | {w['leg_sections_at_z15 (min x max of each leg)']} |
| Ears, 9 mm below the higher tip | {w['ear_sections_at_z86']} |
| Ears, 4 mm below the higher tip | {w['ear_sections_at_z91']} |
| Tail, mid-height | {w['tail_section_at_z90']} |

## 6. Standing stability

Feet in contact with the floor: **{V['feet_contact']['feet_in_contact']}** (footprint x {V['feet_contact']['footprint_x']}, y {V['feet_contact']['footprint_y']} mm). Uniform-density centre of mass:

| Pose | Centre of mass (mm) | Margin to edge of support polygon (mm) | Tilt needed to tip |
|---|---|---|---|
{st}

## 7. Slicing

Slicer: **{S['slicer']}**. Settings: `{S['settings']}`.

| File | Sliced | Warnings | Layers | Est. time | Filament | Supports | Support share of filament | Bed contact (mm²) |
|---|---|---|---|---|---|---|---|---|
{srows}
Downward faces steeper than 45° (not on the bed), from the STL: body {S['body']['overhang_gt45_area_mm2']} mm² (supported),
head {S['head']['overhang_gt45_area_mm2']} mm² and tail {S['tail']['overhang_gt45_area_mm2']} mm² (unsupported; these are the rounded bottom edges,
the eye dimples, mouth groove, underside of the nose and the small flat cap of the socket roof — all short spans).
The plate file was sliced with supports on globally only to prove it loads and slices; in practice enable supports for the body only.

## 8. Known compromises

* **The body needs supports** (about a quarter of its filament) under the belly box, torso and between the staggered legs.
  This is the price of keeping the drawing's boxy belly and four separately visible legs in a single strong part.
* **The ball stalk is printed upright**, so its layers lie across the bending direction. The geometry keeps the snap strain
  low (≈ {hd['est_peak_strain_assembly_percent']} %), but it is the most delicate feature: push the head on straight, do not lever it sideways past its stops.
* The chest under the head stands about 6–8 mm further forward than in the drawing, to carry the ball stud.
* Tail and legs are thicker than the pencil lines, for strength.
* The little squiggle drawn between hind leg and belly is not modelled.
* Joint feel depends on the printer; nothing here has been physically printed. Print the tolerance test first.
* PLA slowly relaxes under constant strain, so joint friction will soften somewhat over months.
"""
open(f"{ROOT}/validation_report.md", "w").write(rep)
print("docs written")
